---
title: "airbnb"
author: "Jung"
output: html_document
---


```{r}
library(rvest)
library(tidyr)
library(dplyr)
library(data.table)
```


```{r preparing for downloading}
airbnb_url <- "http://insideairbnb.com/get-the-data.html"

airbnb_html <- read_html(airbnb_url)

html_node(airbnb_html, "h2") %>%
  html_text() %>%
  trimws(.)

city <- airbnb_html %>%
  html_nodes("h2") %>%
  html_text() %>%
  trimws(.)

# need most up-to-date data - first 3 urls (listings, calender, reviews)
listings_urls <- vector("character")
calender_urls <- vector("character")
reviews_urls <-vector("character")

for (table in 1:length(city)) {
  
  this_listings_urls <- airbnb_html %>%
  html_nodes("tbody") %>%
  .[table] %>%
  html_nodes("a") %>%
  html_attr("href") %>%
  .[1]

  this_calender_urls <- airbnb_html %>%
  html_nodes("tbody") %>%
  .[table] %>%
  html_nodes("a") %>%
  html_attr("href") %>%
  .[2]

  this_reviews_urls <- airbnb_html %>%
  html_nodes("tbody") %>%
  .[table] %>%
  html_nodes("a") %>%
  html_attr("href") %>%
  .[3]
  
  listings_urls <- append(listings_urls, this_listings_urls)
  calender_urls <- append(calender_urls, this_calender_urls)
  reviews_urls <- append(reviews_urls, this_reviews_urls)
}

airbnb_dataframe <- data.frame(city = city,
                            listings_urls = listings_urls,
                            calender_urls = calender_urls,
                            reviews_urls = reviews_urls,
                            stringsAsFactors = F
                            )
```

```{r downloading files}
dir.create("csv_gz_files")

# downloading files for each city

for (i in 1:nrow(airbnb_dataframe)) {
  
  cityname <- strsplit(airbnb_dataframe$city[i], split = ",")[[1]][1]
  
  split_elements_listings <- strsplit(airbnb_dataframe$listings_urls[i], split = "/")[[1]]
  split_elements_calender <- strsplit(airbnb_dataframe$calender_urls[i], split = "/")[[1]]
  split_elements_reviews <- strsplit(airbnb_dataframe$reviews_urls[i], split = "/")[[1]]
    
  file_name_listings <- split_elements_listings[length(split_elements_listings)]
  file_name_calender <- split_elements_calender[length(split_elements_calender)]
  file_name_reviews <- split_elements_reviews[length(split_elements_reviews)]
  
  dir.create(paste0("csv_gz_files/",cityname))
  tryCatch(
        {
          message("Downloading the file...")
          download.file(airbnb_dataframe$listings_urls[i], destfile = paste0("csv_gz_files/",cityname,"/",file_name_listings)) 
        },
        error=function(cond) {
            message(paste("URL does not seem to exist:", url))
            message("Here's the original error message:")
            message(cond)
            return(NA)
        },
        warning=function(cond) {
            message(paste("URL caused a warning:", url))
            message("Here's the original warning message:")
            message(cond)
            return(NULL)
        },
        finally={
            message(paste("Processed URL:", url))
        }
    )    
    download.file(airbnb_dataframe$listings_urls[i], destfile = paste0("csv_gz_files/",cityname,"/",file_name_listings))
  download.file(airbnb_dataframe$calender_urls[i], destfile = paste0("csv_gz_files/",cityname,"/",file_name_calender))
  download.file(airbnb_dataframe$reviews_urls[i], destfile = paste0("csv_gz_files/",cityname,"/",file_name_reviews))
}



tryCatch(
        {
            # Just to highlight: if you want to use more than one 
            # R expression in the "try" part then you'll have to 
            # use curly brackets.
            # 'tryCatch()' will return the last evaluated expression 
            # in case the "try" part was completed successfully

            message("This is the 'try' part")

            readLines(con=url, warn=FALSE) 
            # The return value of `readLines()` is the actual value 
            # that will be returned in case there is no condition 
            # (e.g. warning or error). 
            # You don't need to state the return value via `return()` as code 
            # in the "try" part is not wrapped insided a function (unlike that
            # for the condition handlers for warnings and error below)
        },
        error=function(cond) {
            message(paste("URL does not seem to exist:", url))
            message("Here's the original error message:")
            message(cond)
            # Choose a return value in case of error
            return(NA)
        },
        warning=function(cond) {
            message(paste("URL caused a warning:", url))
            message("Here's the original warning message:")
            message(cond)
            # Choose a return value in case of warning
            return(NULL)
        },
        finally = {
        # NOTE:
        # Here goes everything that should be executed at the end,
        # regardless of success or error.
        # If you want more than one expression to be executed, then you 
        # need to wrap them in curly brackets ({...}); otherwise you could
        # just have written 'finally=<expression>' 
            message(paste("Processed URL:", url))
        }
    )    

```


```{r join the dataset}

calender_df <- fread("csv_gz_files/Amsterdam/calendar.csv.gz") # listing_id
listings_df <- fread("csv_gz_files/Amsterdam/listings.csv.gz") # id
reviews_df <- fread("csv_gz_files/Amsterdam/reviews.csv.gz") # listing_id

col_to_drop <- colnames(listings_df)[grep("url", colnames(listings_df))]

listings_df[, c(col_to_drop) := NULL]

Amsterdam <- listings_df %>%
  inner_join(reviews_df, by = c("id" = "listing_id"), suffix = c("_listings", "_reviews"))

```


